### ISSUE TITLE
code blocks should have some light mode option

### ISSUE THREAD

**Issue by nbitzz** [nbitzz/split.pet#12]
idk how to do this lol

**Comment by ThisCatLikesCrypto** [comment]
This?
![image](https://github.com/user-attachments/assets/cc1ea469-ae2d-472e-9b14-f21bf8dc5a09)
in /src/style/mardown.scss

It looks... fine
![image](https://github.com/user-attachments/assets/393c00d7-3e6e-4f78-9731-a48bdfd18884)

**Comment by nbitzz** [comment]
the text is still like. github dark

**Comment by ThisCatLikesCrypto** [comment]
ohhhh i get what you mean now, i can try but i'm not rly sure how you'd do it either

**Comment by ThisCatLikesCrypto** [comment]
I've tried an astro plugin (astro-expressive-code), it seems to have just worked
![image](https://github.com/user-attachments/assets/038d88f0-aecb-4a07-89df-a34fd21e5bae)
![image](https://github.com/user-attachments/assets/23e62d19-bf72-42f0-af6e-31ee0c8f094e)

**Comment by ThisCatLikesCrypto** [comment]
just ```npx astro add astro-expressive-code``` and then move ```expressiveCode()``` before ```mdx()``` in astro.config.mjs

**Comment by nbitzz** [comment]
ooh okay. i'll take a look soon
