### ISSUE TITLE
use different static image instead of a single color when prefers-reduced-motion is enabled

### ISSUE THREAD

**Issue by nbitzz** [nbitzz/split.pet#13]
these would be good candidates for light and dark mode:
![oyama household at night](https://github.com/user-attachments/assets/f2c106ec-3289-4251-93d1-886fa01c46a4)
![oyama household in the morning](https://github.com/user-attachments/assets/ce087634-27cb-4da0-8025-a84f266f39f7)

**Comment by ThisCatLikesCrypto** [comment]
close this, you did that [here](https://github.com/nbitzz/split.pet/commit/1a50e16f4c1bceacdd512fcb37f70c059def940e)

also whenever i scroll through this repo's commit history i get reminded of the "im tired" post. I just want to tell you that you can absolutely complain about if school is taking a toll on you. this is *your* site after all, and sometimes you might just need to vent and that's ok.

**Comment by nbitzz** [comment]
> close this, you did that [here](https://github.com/nbitzz/split.pet/commit/1a50e16f4c1bceacdd512fcb37f70c059def940e)

Right i did do that

> also whenever i scroll through this repo's commit history i get reminded of the "im tired" post. I just want to tell you that you can absolutely complain about if school is taking a toll on you. this is *your* site after all, and sometimes you might just need to vent and that's ok. 

I'm fine lol ty
